version: '3.8'
services:
  postgres:
    container_name: postgres-sql-coc
    image: postgres:latest
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: cozy_chats
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - cozy-chats
    restart: unless-stopped

  keycloak:
    container_name: keycloak-coc
    image: quay.io/keycloak/keycloak:26.1.4
    ports:
      - 9090:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    networks:
      - cozy-chats
    command:
      - "start-dev"

volumes:
  postgres:
    driver: local
  keycloak:
    driver: local

networks:
  cozy-chats:
    driver: bridge
